### ISSUE TITLE
Some files with only one page crashes the application

### ISSUE THREAD

**Issue by Arpitjain7293** [ViliusSutkus89/pdf2htmlEX-Android#19] opened 2020-04-04 12:23 UTC
Here is the file having only one page
[onepage.pdf](https://github.com/ViliusSutkus89/pdf2htmlEX-Android/files/4431307/onepage.pdf)

**Comment by TomTasche** [comment] 2020-04-04 14:09
How are you running the app? Are you using the sample app?

**Comment by Arpitjain7293** [comment] 2020-04-05 06:45
@TomTasche  yes

**Comment by ViliusSutkus89** [comment] 2020-04-26 20:04
Hello @Arpitjain7293 , thanks for filing the bug.

Have verified that the crash is real and happens to me too. However, the crash also happens in the upstream desktop pdf2htmlEX version too.
Would file a bug on the upstream project ( https://github.com/pdf2htmlEX/pdf2htmlEX ), but your PDF has way too much personal information and I'm not too comfortable passing that around.

Word "Some" in the title implies that you have other affected PDFs. Any chance they are less personal?

**Comment by ViliusSutkus89** [comment] 2023-12-28 07:16
@Arpitjain7293 , just letting you know, that the problem is fixed in pdf2htmlEX-Android-0.18.20 . Here's a screenshot of your pdf opened in the current [Documenter](https://github.com/ViliusSutkus89/Documenter/) version:

![image](https://github.com/ViliusSutkus89/pdf2htmlEX-Android/assets/812793/5fe0b8be-77d8-4ed0-9041-35c89ed9da16)

**Closed by ViliusSutkus89** 2023-12-28 07:16 UTC
Labels: upstream-bug
